Repository dnd-side-project/dnd-10th-7-backend, pull requests merged in 2024-02, with the labels that each got.

#4 Logback #3
  build.gradle
  src/main/resources/logback-spring.xml
Labels: 🔧 Setting

#6 Global Exception 및 Handler #5
  src/main/java/com/sendback/global/exception/BaseException.java
  src/main/java/com/sendback/global/exception/ExceptionType.java
  src/main/java/com/sendback/global/exception/GlobalExceptionHandler.java
  src/main/java/com/sendback/global/exception/response/ErrorResponse.java
  src/main/java/com/sendback/global/exception/response/ExceptionResponse.java
  src/main/java/com/sendback/global/exception/type/BadRequestException.java
  src/main/java/com/sendback/global/exception/type/ForbiddenException.java
  src/main/java/com/sendback/global/exception/type/NotFoundException.java
Labels: ✨Feat

#8 카카오/구글 소셜로그인, jwt, spring security 설정
  .github/pull_request_template.md
  build.gradle
  src/main/java/com/sendback/SendbackApplication.java
  src/main/java/com/sendback/domain/auth/controller/AuthController.java
  src/main/java/com/sendback/domain/auth/dto/SocialUserInfo.java
  src/main/java/com/sendback/domain/auth/dto/Token.java
  src/main/java/com/sendback/domain/auth/dto/request/RefreshTokenRequestDto.java
  src/main/java/com/sendback/domain/auth/dto/response/TokensResponseDto.java
  src/main/java/com/sendback/domain/auth/exception/AuthExceptionType.java
  src/main/java/com/sendback/domain/auth/service/AuthService.java
  src/main/java/com/sendback/domain/auth/service/GoogleService.java
  src/main/java/com/sendback/domain/auth/service/KakaoService.java
  src/main/java/com/sendback/domain/user/entity/User.java
  src/main/java/com/sendback/domain/user/repository/UserRepository.java
  src/main/java/com/sendback/global/common/ApiResponse.java
  src/main/java/com/sendback/global/common/BaseEntity.java
  src/main/java/com/sendback/global/common/UserId.java
  src/main/java/com/sendback/global/common/constants/Career.java
  src/main/java/com/sendback/global/common/constants/Gender.java
  src/main/java/com/sendback/global/common/constants/Level.java
  src/main/java/com/sendback/global/common/constants/SocialType.java
  src/main/java/com/sendback/global/config/auth/ExceptionHandlerFilter.java
  src/main/java/com/sendback/global/config/auth/JwtAuthenticationEntryPoint.java
  src/main/java/com/sendback/global/config/auth/JwtAuthenticationFilter.java
  src/main/java/com/sendback/global/config/auth/SecurityConfig.java
  src/main/java/com/sendback/global/config/auth/UserAuthentication.java
  src/main/java/com/sendback/global/config/auth/UserIdArgumentResolver.java
  src/main/java/com/sendback/global/config/auth/WebConfig.java
  src/main/java/com/sendback/global/config/jwt/JwtProvider.java
  src/main/java/com/sendback/global/config/redis/RedisConfig.java
  src/main/java/com/sendback/global/config/redis/RedisService.java
  src/main/java/com/sendback/global/exception/GlobalExceptionHandler.java
  src/main/java/com/sendback/global/exception/response/ExceptionResponse.java
  src/main/java/com/sendback/global/exception/type/UnAuthorizedException.java
Labels: ✨Feat

#11 fix : 시큐리티 관련 오류 해결 #10
  src/main/java/com/sendback/global/config/auth/SecurityConfig.java
Labels: 🔨 Fix

#18 project 관련 API, test 코드 초반 셋팅 #7 #13
  build.gradle
  src/docs/asciidoc/api/project.adoc
  src/main/java/com/sendback/domain/field/entity/Field.java
  src/main/java/com/sendback/domain/field/exception/FieldExceptionType.java
  src/main/java/com/sendback/domain/field/repository/FieldRepository.java
  src/main/java/com/sendback/domain/field/service/FieldService.java
  src/main/java/com/sendback/domain/project/controller/ProjectController.java
  src/main/java/com/sendback/domain/project/dto/request/SaveProjectRequest.java
  src/main/java/com/sendback/domain/project/dto/request/UpdateProjectRequest.java
  src/main/java/com/sendback/domain/project/dto/response/ProjectIdResponse.java
  src/main/java/com/sendback/domain/project/entity/Project.java
  src/main/java/com/sendback/domain/project/entity/ProjectImage.java
  src/main/java/com/sendback/domain/project/entity/ProjectParticipantCount.java
  src/main/java/com/sendback/domain/project/entity/ProjectPull.java
  src/main/java/com/sendback/domain/project/exception/ProjectExceptionType.java
  src/main/java/com/sendback/domain/project/repository/ProjectImageRepository.java
  src/main/java/com/sendback/domain/project/repository/ProjectRepository.java
  src/main/java/com/sendback/domain/project/service/ProjectService.java
  src/main/java/com/sendback/domain/user/repository/UserRepository.java
  src/main/java/com/sendback/domain/user/service/UserService.java
  src/main/java/com/sendback/global/common/constants/Progress.java
  src/main/java/com/sendback/global/config/image/FilePathUtils.java
  src/main/java/com/sendback/global/config/image/S3Config.java
  src/main/java/com/sendback/global/config/image/S3SaveDir.java
  src/main/java/com/sendback/global/config/image/exception/ImageExceptionType.java
  src/main/java/com/sendback/global/config/image/service/ImageService.java
  src/main/java/com/sendback/global/config/image/service/S3FileService.java
  src/main/java/com/sendback/global/exception/GlobalExceptionHandler.java
  src/main/java/com/sendback/global/exception/type/ImageException.java
  src/test/java/com/sendback/SendbackApplicationTests.java
  src/test/java/com/sendback/domain/auth/controller/AuthControllerDocsTest.java
  src/test/java/com/sendback/domain/field/persister/FieldTestPersister.java
  src/test/java/com/sendback/domain/field/repository/FieldRepositoryTest.java
  src/test/java/com/sendback/domain/field/service/FieldServiceTest.java
  src/test/java/com/sendback/domain/project/controller/ProjectControllerTest.java
  src/test/java/com/sendback/domain/project/entity/ProgressTest.java
  src/test/java/com/sendback/domain/project/fixture/ProjectFixture.java
  src/test/java/com/sendback/domain/project/persister/ProjectImageTestPersister.java
  src/test/java/com/sendback/domain/project/persister/ProjectTestPersister.java
  src/test/java/com/sendback/domain/project/repository/ProjectImageRepositoryTest.java
  src/test/java/com/sendback/domain/project/service/ProjectServiceTest.java
  src/test/java/com/sendback/domain/user/fixture/UserFixture.java
  src/test/java/com/sendback/domain/user/persister/UserTestPersister.java
  src/test/java/com/sendback/global/ControllerTest.java
  src/test/java/com/sendback/global/Persister.java
  src/test/java/com/sendback/global/RepositoryTest.java
  src/test/java/com/sendback/global/ServiceTest.java
  src/test/java/com/sendback/global/config/RestDocsSupport.java
  src/test/java/com/sendback/global/config/TestJpaConfig.java
  src/test/resources/application-test.yml
Labels: ✨Feat, ✅ Test

#20 좋아요 반응, 스크랩 클릭 API #16
  src/docs/asciidoc/api/like.adoc
  src/docs/asciidoc/api/project.adoc
  src/docs/asciidoc/api/scrap.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/sendback/domain/like/controller/LikeController.java
  src/main/java/com/sendback/domain/like/dto/response/ReactLikeResponse.java
  src/main/java/com/sendback/domain/like/entity/Like.java
  src/main/java/com/sendback/domain/like/repository/LikeRepository.java
  src/main/java/com/sendback/domain/like/service/LikeService.java
  src/main/java/com/sendback/domain/scrap/controller/ScrapController.java
  src/main/java/com/sendback/domain/scrap/dto/response/ClickScrapResponse.java
  src/main/java/com/sendback/domain/scrap/entity/Scrap.java
  src/main/java/com/sendback/domain/scrap/repository/ScrapRepository.java
  src/main/java/com/sendback/domain/scrap/service/ScrapService.java
  src/test/java/com/sendback/domain/auth/controller/AuthControllerDocsTest.java
  src/test/java/com/sendback/domain/like/controller/LikeControllerTest.java
  src/test/java/com/sendback/domain/like/fixture/LikeFixture.java
  src/test/java/com/sendback/domain/like/persister/LikeTestPersister.java
  src/test/java/com/sendback/domain/like/repository/LikeRepositoryTest.java
  src/test/java/com/sendback/domain/like/service/LikeServiceTest.java
  src/test/java/com/sendback/domain/project/controller/ProjectControllerTest.java
  src/test/java/com/sendback/domain/scrap/controller/ScrapControllerTest.java
  src/test/java/com/sendback/domain/scrap/fixture/ScrapFixture.java
  src/test/java/com/sendback/domain/scrap/persister/ScrapTestPersister.java
  src/test/java/com/sendback/domain/scrap/repository/ScrapRepositoryTest.java
  src/test/java/com/sendback/domain/scrap/service/ScrapServiceTest.java
  src/test/java/com/sendback/global/ControllerTest.java
  src/test/java/com/sendback/global/RepositoryTest.java
Labels: ✨Feat, ✅ Test

#26 나의 정보 수정, 나의 정보 조회 api #25
  src/main/java/com/sendback/domain/feedback/repository/FeedbackSubmitRepository.java
  src/main/java/com/sendback/domain/field/repository/FieldRepository.java
  src/main/java/com/sendback/domain/like/repository/LikeRepository.java
  src/main/java/com/sendback/domain/project/repository/ProjectRepository.java
  src/main/java/com/sendback/domain/user/controller/UserController.java
  src/main/java/com/sendback/domain/user/dto/request/UpdateUserInfoRequestDto.java
  src/main/java/com/sendback/domain/user/dto/response/UpdateUserInfoResponseDto.java
  src/main/java/com/sendback/domain/user/dto/response/UserInfoResponseDto.java
  src/main/java/com/sendback/domain/user/entity/Career.java
  src/main/java/com/sendback/domain/user/entity/Level.java
  src/main/java/com/sendback/domain/user/entity/User.java
  src/main/java/com/sendback/domain/user/exception/UserExceptionType.java
  src/main/java/com/sendback/domain/user/service/UserService.java
  src/test/java/com/sendback/domain/feedback/repository/FeedbackSubmitRepositoryTest.java
  src/test/java/com/sendback/domain/field/persister/FieldTestPersister.java
  src/test/java/com/sendback/domain/field/repository/FieldRepositoryTest.java
  src/test/java/com/sendback/domain/like/repository/LikeRepositoryTest.java
  src/test/java/com/sendback/domain/project/repository/ProjectImageRepositoryTest.java
  src/test/java/com/sendback/domain/project/repository/ProjectRepositoryTest.java
  src/test/java/com/sendback/domain/scrap/repository/ScrapRepositoryTest.java
  src/test/java/com/sendback/domain/user/controller/UserControllerTest.java
  src/test/java/com/sendback/domain/user/fixture/UserFixture.java
  src/test/java/com/sendback/domain/user/service/UserServiceTest.java
Labels: ✨Feat, ✅ Test

#28 프로젝트 상세 조회 api 구현 #23
  src/docs/asciidoc/api/feedback.adoc
  src/docs/asciidoc/api/like.adoc
  src/docs/asciidoc/api/project.adoc
  src/docs/asciidoc/api/scrap.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/com/sendback/domain/comment/entity/Comment.java
  src/main/java/com/sendback/domain/feedback/controller/FeedbackController.java
  src/main/java/com/sendback/domain/feedback/dto/response/FeedbackDetailResponseDto.java
  src/main/java/com/sendback/domain/feedback/service/FeedbackService.java
  src/main/java/com/sendback/domain/field/entity/Field.java
  src/main/java/com/sendback/domain/field/service/FieldService.java
  src/main/java/com/sendback/domain/like/repository/LikeRepository.java
  src/main/java/com/sendback/domain/project/controller/ProjectController.java
  src/main/java/com/sendback/domain/project/dto/request/SaveProjectRequestDto.java
  src/main/java/com/sendback/domain/project/dto/request/UpdateProjectRequestDto.java
  src/main/java/com/sendback/domain/project/dto/response/ProjectDetailResponseDto.java
  src/main/java/com/sendback/domain/project/entity/Progress.java
  src/main/java/com/sendback/domain/project/entity/Project.java
  src/main/java/com/sendback/domain/project/service/ProjectService.java
  src/main/java/com/sendback/domain/scrap/repository/ScrapRepository.java
  src/main/java/com/sendback/domain/user/dto/request/SignUpRequestDto.java
  src/main/java/com/sendback/domain/user/dto/request/UpdateUserInfoRequestDto.java
  src/main/java/com/sendback/domain/user/entity/Career.java
  src/main/java/com/sendback/domain/user/entity/Gender.java
  src/main/java/com/sendback/domain/user/entity/User.java
  src/main/java/com/sendback/domain/user/service/UserService.java
  src/main/java/com/sendback/global/common/constants/FieldName.java
  src/main/java/com/sendback/global/config/auth/SecurityConfig.java
  src/test/java/com/sendback/domain/feedback/controller/FeedbackControllerTest.java
  src/test/java/com/sendback/domain/feedback/persister/FeedbackSubmitTestPersister.java
  src/test/java/com/sendback/domain/feedback/persister/FeedbackTestPersister.java
  src/test/java/com/sendback/domain/feedback/repository/FeedbackSubmitRepositoryTest.java
  src/test/java/com/sendback/domain/field/fixture/FieldFixture.java
  src/test/java/com/sendback/domain/field/persister/FieldTestPersister.java
  src/test/java/com/sendback/domain/field/repository/FieldRepositoryTest.java
  src/test/java/com/sendback/domain/field/service/FieldServiceTest.java
  src/test/java/com/sendback/domain/like/persister/LikeTestPersister.java
  src/test/java/com/sendback/domain/like/repository/LikeRepositoryTest.java
  src/test/java/com/sendback/domain/project/controller/ProjectControllerTest.java
  src/test/java/com/sendback/domain/project/entity/ProgressTest.java
  src/test/java/com/sendback/domain/project/fixture/ProjectFixture.java
  src/test/java/com/sendback/domain/project/persister/ProjectImageTestPersister.java
  src/test/java/com/sendback/domain/project/persister/ProjectTestPersister.java
  src/test/java/com/sendback/domain/project/repository/ProjectImageRepositoryTest.java
  src/test/java/com/sendback/domain/project/repository/ProjectRepositoryTest.java
  src/test/java/com/sendback/domain/project/service/ProjectServiceTest.java
  src/test/java/com/sendback/domain/scrap/persister/ScrapTestPersister.java
  src/test/java/com/sendback/domain/scrap/repository/ScrapRepositoryTest.java
  src/test/java/com/sendback/domain/user/controller/UserControllerTest.java
  src/test/java/com/sendback/domain/user/fixture/UserFixture.java
  src/test/java/com/sendback/domain/user/persister/UserTestPersister.java
  src/test/java/com/sendback/domain/user/repository/UserRepositoryTest.java
  src/test/java/com/sendback/domain/user/service/UserServiceTest.java
Labels: ✨Feat, 🔨 Fix, ✅ Test

#29 test : csrf visible 삭제
  src/test/java/com/sendback/domain/auth/controller/AuthControllerTest.java
  src/test/java/com/sendback/domain/feedback/controller/FeedbackControllerTest.java
  src/test/java/com/sendback/domain/feedback/service/FeedbackServiceTest.java
  src/test/java/com/sendback/domain/like/controller/LikeControllerTest.java
  src/test/java/com/sendback/domain/project/controller/ProjectControllerTest.java
  src/test/java/com/sendback/domain/scrap/controller/ScrapControllerTest.java
  src/test/java/com/sendback/domain/user/controller/UserControllerTest.java
  src/test/java/com/sendback/global/ControllerTest.java
Labels: ✅ Test

#30 내가 등록한 프로젝트 조회 및 이전 api 점검 /#27
  build.gradle
  src/docs/asciidoc/api/auth.adoc
  src/docs/asciidoc/api/user.adoc
  src/main/java/com/sendback/domain/auth/service/GoogleService.java
  src/main/java/com/sendback/domain/auth/service/KakaoService.java
  src/main/java/com/sendback/domain/project/entity/Project.java
  src/main/java/com/sendback/domain/project/entity/ProjectPull.java
  src/main/java/com/sendback/domain/project/exception/ProjectExceptionType.java
  src/main/java/com/sendback/domain/project/repository/ProjectRepository.java
  src/main/java/com/sendback/domain/project/repository/ProjectRepositoryCustom.java
  src/main/java/com/sendback/domain/project/repository/ProjectRepositoryImpl.java
  src/main/java/com/sendback/domain/user/controller/UserController.java
  src/main/java/com/sendback/domain/user/dto/response/RegisteredProjectResponseDto.java
  src/main/java/com/sendback/domain/user/exception/UserExceptionType.java
  src/main/java/com/sendback/domain/user/service/UserService.java
  src/main/java/com/sendback/global/common/CustomPage.java
  src/main/java/com/sendback/global/config/querydsl/QuerydslConfig.java
  src/test/java/com/sendback/domain/auth/controller/AuthControllerTest.java
  src/test/java/com/sendback/domain/feedback/controller/FeedbackControllerTest.java
  src/test/java/com/sendback/domain/like/controller/LikeControllerTest.java
  src/test/java/com/sendback/domain/project/controller/ProjectControllerTest.java
  src/test/java/com/sendback/domain/project/entity/ProgressTest.java
  src/test/java/com/sendback/domain/scrap/controller/ScrapControllerTest.java
  src/test/java/com/sendback/domain/user/controller/UserControllerTest.java
Labels: 🔧 Chore, ✨Feat, 🔨 Fix, ✅ Test

#34 프로젝트 전체 조회(메인 페이지), 끌올 api #32
  src/docs/asciidoc/api/project.adoc
  src/main/java/com/sendback/domain/feedback/dto/response/FeedbackDetailResponseDto.java
  src/main/java/com/sendback/domain/feedback/dto/response/FeedbackResponseDto.java
  src/main/java/com/sendback/domain/project/controller/ProjectController.java
  src/main/java/com/sendback/domain/project/dto/request/SaveProjectRequestDto.java
  src/main/java/com/sendback/domain/project/dto/request/UpdateProjectRequestDto.java
  src/main/java/com/sendback/domain/project/dto/response/GetProjectsResponseDto.java
  src/main/java/com/sendback/domain/project/dto/response/ProjectDetailResponseDto.java
  src/main/java/com/sendback/domain/project/dto/response/PullUpProjectResponseDto.java
  src/main/java/com/sendback/domain/project/entity/Project.java
  src/main/java/com/sendback/domain/project/entity/ProjectPull.java
  src/main/java/com/sendback/domain/project/exception/ProjectExceptionType.java
  src/main/java/com/sendback/domain/project/repository/ProjectRepositoryCustom.java
  src/main/java/com/sendback/domain/project/repository/ProjectRepositoryImpl.java
  src/main/java/com/sendback/domain/project/service/ProjectService.java
  src/main/java/com/sendback/domain/scrap/repository/ScrapRepository.java
  src/main/java/com/sendback/domain/user/dto/request/SignUpRequestDto.java
  src/main/java/com/sendback/domain/user/dto/request/UpdateUserInfoRequestDto.java
  src/main/java/com/sendback/domain/user/dto/response/UpdateUserInfoResponseDto.java
  src/main/java/com/sendback/domain/user/dto/response/UserInfoResponseDto.java
  src/main/java/com/sendback/domain/user/entity/Level.java
  src/main/java/com/sendback/domain/user/entity/User.java
  src/main/java/com/sendback/domain/user/service/UserService.java
  src/main/java/com/sendback/global/common/constants/FieldName.java
  src/main/java/com/sendback/global/config/auth/SecurityConfig.java
  src/main/java/com/sendback/global/util/CustomDateUtil.java
  src/test/java/com/sendback/domain/feedback/controller/FeedbackControllerTest.java
  src/test/java/com/sendback/domain/feedback/fixture/FeedbackFixture.java
  src/test/java/com/sendback/domain/feedback/service/FeedbackServiceTest.java
  src/test/java/com/sendback/domain/project/controller/ProjectControllerTest.java
  src/test/java/com/sendback/domain/project/fixture/ProjectFixture.java
  src/test/java/com/sendback/domain/project/persister/ProjectTestPersister.java
  src/test/java/com/sendback/domain/project/repository/ProjectRepositoryTest.java
  src/test/java/com/sendback/domain/project/service/ProjectServiceTest.java
  src/test/java/com/sendback/domain/user/controller/UserControllerTest.java
  src/test/java/com/sendback/domain/user/service/UserServiceTest.java
Labels: ✨Feat, 💡Refactor, ✅ Test

#39 feat : 더미 데이터 생성 #36
  src/main/java/com/sendback/global/dummy/FeedbackDummy.java
  src/main/java/com/sendback/global/dummy/FieldDummy.java
  src/main/java/com/sendback/global/dummy/LikeDummy.java
  src/main/java/com/sendback/global/dummy/ProjectDummy.java
  src/main/java/com/sendback/global/dummy/ProjectImageDummy.java
  src/main/java/com/sendback/global/dummy/ScrapDummy.java
  src/main/java/com/sendback/global/dummy/UserDummy.java
Labels: ✨Feat

#41 스케줄러 #40
  src/main/java/com/sendback/SendbackApplication.java
  src/main/java/com/sendback/domain/feedback/entity/Feedback.java
  src/main/java/com/sendback/domain/feedback/repository/FeedbackRepository.java
  src/main/java/com/sendback/domain/feedback/service/FeedbackSchedulerService.java
  src/main/java/com/sendback/domain/project/repository/ProjectRepository.java
  src/main/java/com/sendback/domain/project/service/ProjectSchedulerService.java
  src/main/java/com/sendback/domain/user/entity/User.java
  src/main/java/com/sendback/domain/user/repository/UserRepository.java
  src/main/java/com/sendback/domain/user/service/UserSchedulerService.java
  src/test/java/com/sendback/domain/feedback/repository/FeedbackRepositoryTest.java
  src/test/java/com/sendback/domain/project/repository/ProjectRepositoryTest.java
  src/test/java/com/sendback/domain/user/repository/UserRepositoryTest.java
Labels: ✨Feat

#43 응답값 및 param 리팩토링 /#42
  src/main/java/com/sendback/domain/feedback/dto/response/FeedbackDetailResponseDto.java
  src/main/java/com/sendback/domain/feedback/dto/response/FeedbackResponseDto.java
  src/main/java/com/sendback/domain/feedback/dto/response/GetFeedbacksResponse.java
  src/main/java/com/sendback/domain/feedback/service/FeedbackService.java
  src/main/java/com/sendback/domain/project/controller/ProjectController.java
  src/test/java/com/sendback/domain/feedback/controller/FeedbackControllerTest.java
  src/test/java/com/sendback/domain/feedback/fixture/FeedbackFixture.java
  src/test/java/com/sendback/domain/feedback/service/FeedbackServiceTest.java
  src/test/java/com/sendback/domain/project/controller/ProjectControllerTest.java
Labels: 💡Refactor

#46 전체적인 에러 수정 및 리팩토링/#45
  src/main/java/com/sendback/domain/feedback/repository/FeedbackSubmitRepository.java
  src/main/java/com/sendback/domain/like/repository/LikeRepository.java
  src/main/java/com/sendback/domain/project/repository/ProjectRepository.java
  src/main/java/com/sendback/domain/project/repository/ProjectRepositoryCustom.java
  src/main/java/com/sendback/domain/project/repository/ProjectRepositoryImpl.java
  src/main/java/com/sendback/domain/project/service/ProjectService.java
  src/main/java/com/sendback/domain/user/exception/UserExceptionType.java
  src/main/java/com/sendback/domain/user/service/UserService.java
  src/test/java/com/sendback/domain/feedback/repository/FeedbackSubmitRepositoryTest.java
  src/test/java/com/sendback/domain/like/repository/LikeRepositoryTest.java
  src/test/java/com/sendback/domain/project/repository/ProjectRepositoryTest.java
  src/test/java/com/sendback/domain/user/service/UserServiceTest.java
Labels: 🔨 Fix, 💡Refactor

#48 피드백 작성자가 피드백 제출 시 예외처리 #42
  src/main/java/com/sendback/domain/feedback/entity/Feedback.java
  src/main/java/com/sendback/domain/feedback/exception/FeedbackExceptionType.java
  src/main/java/com/sendback/domain/feedback/service/FeedbackService.java
  src/main/java/com/sendback/domain/project/dto/response/GetProjectsResponseDto.java
  src/main/java/com/sendback/domain/project/entity/Project.java
  src/test/java/com/sendback/domain/feedback/service/FeedbackServiceTest.java
Labels: 💡Refactor
